services:
  eureka-server-service:
    container_name: eureka-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8761"
    networks:
      hls-lab-network:

networks:
  hls-lab-network:
    external: true